name: Lint
on: [push, pull_request, workflow_dispatch]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=2m0s
          skip-go-installation: true
          version: v1.41.1
